rabbit1:
  image: bijukunjummen/rabbitmq-server:3.7.0
  hostname: rabbit1
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin123


rabbit2:
  image: bijukunjummen/rabbitmq-server:3.7.0
  hostname: rabbit2
  links:
    - rabbit1
  environment: 
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true


rabbit3:
  image: bijukunjummen/rabbitmq-server:3.7.0
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment: 
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1


haproxy:
  build: ./haproxy
  container_name: rmqha_proxy
  restart: always  
  links:
    - rabbit1
    - rabbit2
    - rabbit3      
  ports:
    - "5672:5672"
    - "15672:15672"  